### ISSUE TITLE
Why targeted iOS version is 10?

### ISSUE THREAD

**Issue by olcayertas** [nakajijapan/PhotoSlider#104]
I have tested source files with targeting iOS 9 and it works fine. Why the library targets iOS 10 in podspec?

**Comment by yhkaplan** [comment]
There are a few possible reasons that I’ve listed below, but @nakajijapan can answer whether he thinks the pros outweigh the cons below. In the meantime, if you’re in a hurry, then using a forked version seems like a temporary workaround.

1. Lack of access to test devices with that version
2. Increased time required for testing
3. Little demand

**Comment by nakajijapan** [comment]
Hi, @olcayertas 
I have the policy that we support one before, iOS10.
So, I glad you to fork the our repository for supporting iOS9.
