### ISSUE TITLE
Autorotation problem

### ISSUE THREAD

**Issue by famAlex** [nakajijapan/PhotoSlider#16]
Hi, I'm implementing your work into my project (thank you for sharing) and it seams I was able to do it correctly.

Unfortunately I've got problems during rotation while I'm inside the PhotoSlider.ViewController: moving the orientation from there produces a weird disposition of the view. It seams like it misses the new framework size.
Because I'm a beginner I wasn't able to solve it alone. Could you give an hint about it?
Thank you
Alessandro

**Comment by nakajijapan** [comment]
Oh, Sorry. This project doesn't support the orientation. 
To begin with, I didn't think the orientation.

But, I will work hard in order to meet your expectations.

**Comment by famAlex** [comment]
You're very kind, thank you for your interest.
I found PhotoSlider very nice and exactly what I needed for!

**Comment by nakajijapan** [comment]
Hi, @famAlex 

I supported the orientation. You can use v4.0.0. Please try to check!

![demo_photoslider2](https://cloud.githubusercontent.com/assets/193569/9026568/513fa360-396e-11e5-81bd-c2f57c068161.gif)

**Comment by famAlex** [comment]
Awesome!!
I just checked it and it's perfect, I've done a really good work.
I'm grateful to you for sharing, many thanks again!!

**Comment by famAlex** [comment]
Hi, 
sorry for being here again but I noticed that the issue remains on iPad but I don't know if your project was targeted for iPhones only or not.
Kind regards
Alessandro
