### ISSUE TITLE
slider.index = indexPath.row error after pod update

### ISSUE THREAD

**Issue by famAlex** [nakajijapan/PhotoSlider#25]
Hi,
as I wrote in the title, after upgrading from version  0.4.0 to 0.6.0, the line "slider.index = indexPath.row" gives me an error but deleting it my app seams to work correctly.
I just wanted to report for let the instructions up to date.

PS: any plan to fix the rotation behavior on iPad?  
Many thanks

**Comment by nakajijapan** [comment]
Please write code such as this

```
        photoSlider.currentPage = indexPath.row
```

https://github.com/nakajijapan/PhotoSlider/blob/master/Example/PhotoSliderDemo/ViewController.swift#L122

**Comment by nakajijapan** [comment]
https://github.com/nakajijapan/PhotoSlider/pull/20

In this issue, we fixed in order to know current page when controller was dismissed.

**Comment by nakajijapan** [comment]
@famAlex

About iPad. For now, It is not in current planning.
I try as much as I can.

**Comment by famAlex** [comment]
Thank you for the advice and for the reply, I really appreciate it.
