### ISSUE TITLE
StatusBar shown only device

### ISSUE THREAD

**Issue by seapy** [nakajijapan/PhotoSlider#35]
Statusbar is hidden with simulator, but statusbar is shown with device.

And in 4 inch(ex iPhone 5) device, close button not touched well(this issue also with device, not simulator)

**Comment by nakajijapan** [comment]
Thank you for finding it. I will check it and get back to you as soon as possible.

**Comment by orazz** [comment]
Something is missing here (share button)

**Comment by nakajijapan** [comment]
> Statusbar is hidden with simulator, but statusbar is shown with device.

I could not verify this phenomenon at a device of iPhone6Plus.
I have a device of iPhone6Plus only. If you have that device, tell me a cause and please give me a Pull request.

**Comment by orazz** [comment]
I have iPhone 6 (iOS 9.2) and i have this issue too

p.s.
Could you please add reload button. When some links not working and get error

**Comment by seapy** [comment]
i fix this problem use `UIApplication.shared.setStatusBarHidden(true, with: .fade)`

**Comment by NicosKaralis** [comment]
@seapy this is the wrong way to hide the status bar and currently it does not work

The correct way is to override the `prefersStatusBarHidden` variable, like so:

    override var prefersStatusBarHidden: Bool {
      get {
        return internalShouldPresentStatusBar
      }
    }
