### ISSUE TITLE
Add caption to photoviews

### ISSUE THREAD

**Issue by aymeba** [nakajijapan/PhotoSlider#41]
Hello,

thanks for this great slider :) Can we put some captions/titles into photo view?

**Comment by nakajijapan** [comment]
I will add it as option!

**Comment by nakajijapan** [comment]
I should consider the design...

**Comment by nakajijapan** [comment]
@aymeba 

Hi, 

I added a feature of showing a caption.
You can use v0.10.0.

**Comment by nakajijapan** [comment]
![simulator screen shot 2015 11 10 21 51 09](https://cloud.githubusercontent.com/assets/193569/11062782/3e5e914a-87f5-11e5-8740-670c8bccff3c.png)
![simulator screen shot 2015 11 10 21 51 14](https://cloud.githubusercontent.com/assets/193569/11062783/3e66a542-87f5-11e5-995b-a9849af9c770.png)

**Comment by aymeba** [comment]
Great work :+1:  :) Thanks!!
