### ISSUE TITLE
application crash while close fullscreen when image is loading

### ISSUE THREAD

**Issue by Pyrolr** [nakajijapan/PhotoSlider#48]
Application crash with: fatal error: unexpectedly found nil while unwrapping an Optional value 
when click close while image is loading in full screen page control view

Check on Swift 2, iOS 9

**Comment by nakajijapan** [comment]
Thank you for reporting. 
Wait a little because to fix.

**Comment by nakajijapan** [comment]
@Pyrolr 

Hi, 

I fixed it.
You can use v0.11.1.

**Comment by Pyrolr** [comment]
@nakajijapan thanks for really quick response and resolution
