### ISSUE TITLE
Pod issue

### ISSUE THREAD

**Issue by raymond-auhwa** [nakajijapan/PhotoSlider#65]
Pod doesn't grab the latest version.

**Comment by nakajijapan** [comment]
Hi, @raymond-auhwa 

I could upload the latest version when I updated CocoaPods for gems...
Please, retry to grab the latest version.

**Comment by Raymond-OJam** [comment]
Hi, @nakajijapan 
It works, thanks a lot.

**Comment by RaymondEnergyOne** [comment]
Hi @nakajijapan 
It works now, thanks a lot.

**Comment by raymond-auhwa** [comment]
Hi @nakajijapan 
It works now. 
Thanks a lot.
