### ISSUE TITLE
Version for swift 3

### ISSUE THREAD

**Issue by Dougbh** [nakajijapan/PhotoSlider#66]
When running on xcode 8 it shows a lot of error, when it will be unstable to swift 3

**Comment by nakajijapan** [comment]
Sorry!!!!! 
I will fix it soon!

**Comment by nakajijapan** [comment]
https://github.com/nakajijapan/PhotoSlider/releases/tag/0.14.2

@Dougbh  I fixed some bug. Please check 0.14.2.

### Rrequired

- Xcode 8.2+
- Swift 3.0+
