### ISSUE TITLE
Code not compiling 

### ISSUE THREAD

**Issue by kunalgupta1593** [nakajijapan/PhotoSlider#68]
Kingfisher framewor not found..

**Comment by nakajijapan** [comment]
I will fix it soon! Sorry...

**Comment by chitvan832** [comment]
you didnt fix it yet

**Comment by nakajijapan** [comment]
Currenty, you need to work the below tasks.

1. carthage bootstrap
1. add Kingfisher and Photoslider framework in embedded binary
