### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by dariopellegrini** [nakajijapan/PhotoSlider#69]
In previous versions of PhotoSlider was possible zooming images once open. With 0.14.1 is not possible anymore.

The init code

var photos: [PhotoSlider.Photo] = []
for image in images {
photos += [PhotoSlider.Photo(imageURL:image, caption: "")]
}
let slider = PhotoSlider.ViewController(photos: photos )
slider.currentPage = index
slider.visiblePageControl = false
 viewController.present(slider, animated: true, completion: nil)

**Comment by seapy** [comment]
I have a same problem

**Comment by nakajijapan** [comment]
Updated.

https://github.com/nakajijapan/PhotoSlider/releases/tag/0.14.3

**Comment by dariopellegrini** [comment]
Thank you :)
