### ISSUE TITLE
Possibility to set number of caption lines

### ISSUE THREAD

**Issue by marten83** [nakajijapan/PhotoSlider#79]
It would be great if it were possible to set the number of lines for the captions. Now it is fixed to 3

**Comment by nakajijapan** [comment]
@marten83 

Do you mean that you want to be able to change the number of lines for the captions?
OK, I will try it.

**Comment by marten83** [comment]
That's exactly what i mean

**Comment by nakajijapan** [comment]
Hi, @marten83

I adopted this request at v0.17. Please check v0.17.
https://github.com/nakajijapan/PhotoSlider/releases/tag/0.17.0

**Comment by marten83** [comment]
Works like a charm! Thank you very much.
