### ISSUE TITLE
crash in iOs 11

### ISSUE THREAD

**Issue by marten83** [nakajijapan/PhotoSlider#89]
In iOs 11 PhotoSlider crach on "effectView.addSubview(backgroundView)" in ViewController.swift. Works with "effectView.contentView.addSubview(backgroundView)"

**Comment by AndriiPetrovDev** [comment]
Please just replace `ViewController.swift`  89

`effectView.addSubview(backgroundView)`

with

`effectView.contentView.addSubview(backgroundView)`

**Comment by nakajijapan** [comment]
hi, I'm sorry for late.

Maybe I fixed it. Could you confirm it at v0.18.0

**Comment by Faari7** [comment]
i am also facing the same issue.
